# Use a standard Python base image
FROM python:3.8-slim

# Install the required libraries for Kafka, Elasticsearch, and Neo4j communication
RUN pip install kafka-python elasticsearch neo4j

# Copy your application code to the container
COPY ./consumer_app /app

# Set the working directory
WORKDIR /app

# Set the command to run your application
CMD ["python", "consumer_app.py"]
