apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: producer-app
  name: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: producer-app
    spec:
      containers:
        - image: producer-app
          name: producer_app
          resources: {}
      restartPolicy: Always
status: {}
